### ISSUE TITLE
NPE on disablePlugin

### ISSUE THREAD

**Issue by SlimeDog** [Block2Block/HubParkour-Legacy#4]
Spigot 1.13.2 latest
HubParkour 1.3.1

NPE on server shutdown:
```
[13:11:33] [Server thread/INFO]: [HubParkour] Disabling HubParkour v1.3.1
[13:11:33] [Server thread/ERROR]: Error occurred while disabling HubParkour v1.3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at io.github.Block2Block.HubParkour.Main.onDisable(Main.java:256) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:371) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:370) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:621) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:766) [spigot-1.13.2.jar-2019-04-05-0743:git-Spigot-f09662d-f40143e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Block2Block** [comment]
That is an issue with closing the database when the database wasn't used. I can fix that quite easily.
